export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = 'USER_FAIL';

export const LOGOUT = 'LOGOUT_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const SEND_CODE_REQUEST = 'SEND_CODE_REQUEST';
export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';
export const SEND_CODE_FAIL = 'SEND_CODE_FAIL';

export const CHECK_CODE_REQUEST = 'CHECK_CODE_REQUEST';
export const CHECK_CODE_SUCCESS = 'CHECK_CODE_SUCCESS';
export const CHECK_CODE_FAIL = 'CHECK_CODE_FAIL';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const PARTY_LOADING = 'PARTY_LOADING';
export const PARTY_LOADED = 'PARTY_LOADED';
export const PARTY_CREATING = 'PARTY_CREATING';
export const PARTY_CREATED = 'PARTY_CREATED';
export const PARTY_ERROR = 'PARTY_ERROR';

export const PARTY_LIST_LOADING = 'PARTY_LIST_LOADING';
export const PARTY_LIST_LOADED = 'PARTY_LIST_LOADED';
export const PARTY_LIST_ERROR = 'PARTY_LIST_ERROR';
